### ISSUE TITLE
Procurement

### ISSUE THREAD

**Issue by mgifford** [VilledeMontreal/politique-libre#3]
How does this fit with the city's IT procurement strategy?

Would like to know what changes might be made to contract boiler plates and default RFPs to ensure that open source is actually an option.

Have some ideas listed here https://github.com/mgifford/open-source-contracting

**Comment by uferrpi** [comment]
The Open Source Policy is not included in the Procurement Policy _per se_. 

However, all business needs that could result in IT RFP's, development, etc. are submitted to a systematic market review which includes the mandatory requirement to check the Open Source market, with additional special parameters. We've been doing this for over a year.   The market review parameters for open source solutions will be published in this repository by the end of the year.

As you might see in our catalog, we have no qualms to use Open Source solutions when there's a ''fit'' between business needs, costs, efforts, risks, etc.

**Comment by mgifford** [comment]
Thanks @uferrpi I do think that there are some times where proprietary solutions are appropriate for sure. However, in public sector procurement, they have really been given the upper hand. I'd be interested in seeing if a mandatory market review that includes open source solutions is able to produce the cultural change that will be needed to have a significant impact on investments in open source technologies. 

If you've got any ideas on what can be done to improve open source procurement that I have missed in my list on GitHub above, please let me know.
