### ISSUE TITLE
Commentaires critiques de FACiL

### ISSUE THREAD

**Issue by mathieugp** [VilledeMontreal/politique-libre#5]
Nos commentaires critiques sur la nouvelle politique de la Ville de Montréal sont en ligne à l'adresse suivante :

[https://facil.qc.ca/comment-polmtl-libre](https://facil.qc.ca/comment-polmtl-libre)

**Comment by psionikangel** [comment]
Merci de vos commentaires.

Nous les évaluerons dans l'optique d'amélioration de nos directives de contribution.

Quant à la politique en elle-même, nous accumulons les commentaires dans le but de publier une version 2 dans le futur.
